SELECT A.ID, A.START_TIME, A.END_TIME
FROM RESERVATION A
WHERE NOT EXISTS (
    SELECT 1
    FROM RESERVATION B
    WHERE B.ID < A.ID AND B.END_TIME > A.START_TIME AND B.START_TIME < A.END_TIME
)
ORDER BY 2;